### ISSUE TITLE
blender: error: unrecognized arguments: --joint_type=HumanML3D

### ISSUE THREAD

**Issue by hdjsjyl** [OpenMotionLab/MotionGPT#28]
HI author,
     It seems no joint_type parameter here.

**Comment by billl-jiang** [comment]
Hi @hdjsjyl 

We have made improvements to the render script, enabling it to automatically detect the joint_type of .npy files instead of requiring manual assignment. As a result, you no longer need to specify the joint_type while keeping other flags unchanged. We have also updated the README to reflect this update.

**Comment by hdjsjyl** [comment]
thank you!
