### ISSUE TITLE
Where the token to enter T5 comes from?

### ISSUE THREAD

**Issue by daidaiershidi** [OpenMotionLab/MotionGPT#7]
Thank you for bringing such interesting work. When reading the paper, I had a confusion. In Figure 2, token from vqvae's codebook (yellow token input to T5). But in Sec. 3.2, you said "we combine the original text vocabulary V_{t} with motion vocabulary V_{m}, which is order-preserving to our motion codebook Z." Does this mean that the token entered into T5 does not come from the codebook of VQVAE (V_{m} is different from Z).

**Comment by ChenFengYe** [comment]
No, the tokens do not come from the codebook directly. We only use the distribution of these tokens rather than the VQ embedding itself.

To ensure a shared distribution between language and motion, we initialize the Motion tokens separately and concatenate them alongside the language tokens. This step ensures a balanced representation that encompasses both modalities. Besides the token embeddings are actively trained during the entirety of stages 2 and 3, ensuring a comprehensive fusion of language and motion knowledge.
