### ISSUE TITLE
Camera location includes nan values.

### ISSUE THREAD

**Issue by ncj0302** [OpenMotionLab/MotionGPT#84]
When I ran the command
『blender/blender --background --python render.py -- --cfg=./configs/render.yaml --dir results/mgpt/debug--Instruct_HumanML3D/samples_2024-03-04-11-42-10 --mode=video』
to render motions to vedio (mp4),
I faced some error about camera location.

![image](https://github.com/OpenMotionLab/MotionGPT/assets/70960240/30c3f807-a066-4da1-8cec-68d07594817c)

And I edited some codes for checking the camera location data, I found the location data are all nan values.
How can I fix it?

![image](https://github.com/OpenMotionLab/MotionGPT/assets/70960240/43705cdb-3dc5-44f6-a35e-bee751524a4d)
![image](https://github.com/OpenMotionLab/MotionGPT/assets/70960240/72b8c95c-2d7c-4eb1-ae84-74856457abb1)

**Comment by billl-jiang** [comment]
Hello,

It seems you're encountering issues with camera location data containing NaN values during rendering. While I haven't come across this specific issue before, it might be related to the data being used for rendering. Have you had a chance to check the `.npy` files intended for rendering? It's possible the issue lies there.

**Comment by ncj0302** [comment]
Hi.

I think there are some outliers in HumanML3D dataset.
Thanks to reply.
